package com.duoc.views;

import javax.swing.JFrame;

import com.duoc.controllers.BicicletaController;
import com.duoc.controllers.FabricanteController;
import com.duoc.controllers.CategoriaController;
import com.duoc.models.Bicicleta;
import com.duoc.models.Categoria;
import com.duoc.models.CustomException;
import com.duoc.models.Fabricante;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class MainWindow extends javax.swing.JFrame {

    private BicicletaController bc = new BicicletaController();
    private FabricanteController fc = new FabricanteController();
    private CategoriaController cc = new CategoriaController();
    
    
    public MainWindow() {
        initComponents();
        estadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFabricantes = new javax.swing.JInternalFrame();
        jLabelIDFabricantes = new javax.swing.JLabel();
        jLabelNombreFabricantes = new javax.swing.JLabel();
        jTextFieldIdFabricantes = new javax.swing.JTextField();
        jTextFieldNombreFabricantes = new javax.swing.JTextField();
        jButtonAgregarFabricantes = new javax.swing.JButton();
        jButtonModificarFabricantes = new javax.swing.JButton();
        jButtonQuitarFabricantes = new javax.swing.JButton();
        jComboBoxIDFabricantes = new javax.swing.JComboBox<>();
        jTextFieldCodigoFabricantes = new javax.swing.JTextField();
        jScrollPaneFabricantes = new javax.swing.JScrollPane();
        jTableFabricantes = new javax.swing.JTable();
        jInternalCategorias = new javax.swing.JInternalFrame();
        jLabelIDCategorias = new javax.swing.JLabel();
        jLabelNombreCategorias = new javax.swing.JLabel();
        jTextFieldIDCategorias = new javax.swing.JTextField();
        jTextFieldNombreCategorias = new javax.swing.JTextField();
        jButtonAgregarCategorias = new javax.swing.JButton();
        jButtonModificarCategorias = new javax.swing.JButton();
        jButtonQuitarCategorias = new javax.swing.JButton();
        jComboBoxIDCategorias = new javax.swing.JComboBox<>();
        jTextFieldCodigoCategorias = new javax.swing.JTextField();
        jScrollPaneCategorias = new javax.swing.JScrollPane();
        jTableCategorias = new javax.swing.JTable();
        jInternalBicicletas = new javax.swing.JInternalFrame();
        jLabelIDBicicletas = new javax.swing.JLabel();
        jLabelModeloBicicletas = new javax.swing.JLabel();
        jLabelTallaBicicletas = new javax.swing.JLabel();
        jLabelSuspensionBicicletas = new javax.swing.JLabel();
        jLabelTransmisionBicicletas = new javax.swing.JLabel();
        jLabelFrenosBicicletas = new javax.swing.JLabel();
        jLabelStockBicicletas = new javax.swing.JLabel();
        jLabelValorBicicletas = new javax.swing.JLabel();
        jComboBoxIDBicicletas = new javax.swing.JComboBox<>();
        jTextFieldCodigoBicicletas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldIDBicicletas = new javax.swing.JTextField();
        jTextFieldModeloBicicletas = new javax.swing.JTextField();
        jTextFieldTallaBicicletas = new javax.swing.JTextField();
        jTextFieldSuspensionBicicletas = new javax.swing.JTextField();
        jTextFieldTransmisionBicicletas = new javax.swing.JTextField();
        jTextFieldFrenosBicicletas = new javax.swing.JTextField();
        jTextFieldStockBicicletas = new javax.swing.JTextField();
        jTextFieldValorBicicletas = new javax.swing.JTextField();
        jButtonAgregarBicicletas = new javax.swing.JButton();
        jButtonEditarBicicletas = new javax.swing.JButton();
        jButtonEliminarBicicletas = new javax.swing.JButton();
        jLabelFabricanteBicicletas = new javax.swing.JLabel();
        jLabelCategoriaBicicletas = new javax.swing.JLabel();
        jComboBoxFabricanteBicicletas = new javax.swing.JComboBox<>();
        jComboBoxCategoriaBicicletas = new javax.swing.JComboBox<>();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuArchivoIngresar = new javax.swing.JMenuItem();
        jMenuArchivoSalir = new javax.swing.JMenuItem();
        jMenuRegistrar = new javax.swing.JMenu();
        jMenuRegistrarBicicleta = new javax.swing.JMenuItem();
        jMenuRegistrarCategoria = new javax.swing.JMenuItem();
        jMenuRegistrarFabricante = new javax.swing.JMenuItem();
        jMenuInformes = new javax.swing.JMenu();
        jMenuInformesBici = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuAyudaAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fabricante");
        getContentPane().setLayout(null);

        jInternalFabricantes.setTitle("Fabricantes");
        jInternalFabricantes.setVisible(true);

        jLabelIDFabricantes.setText("Código:");

        jLabelNombreFabricantes.setText("Nombre:");

        jTextFieldIdFabricantes.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldIdFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdFabricantesActionPerformed(evt);
            }
        });

        jTextFieldNombreFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreFabricantesActionPerformed(evt);
            }
        });

        jButtonAgregarFabricantes.setText("Agregar");
        jButtonAgregarFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFabricantesActionPerformed(evt);
            }
        });

        jButtonModificarFabricantes.setText("Modificar");
        jButtonModificarFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarFabricantesActionPerformed(evt);
            }
        });

        jButtonQuitarFabricantes.setText("Quitar");
        jButtonQuitarFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarFabricantesActionPerformed(evt);
            }
        });

        jComboBoxIDFabricantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombre" }));
        jComboBoxIDFabricantes.setToolTipText("");
        jComboBoxIDFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDFabricantesActionPerformed(evt);
            }
        });

        jTextFieldCodigoFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoFabricantesActionPerformed(evt);
            }
        });

        jTableFabricantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFabricantes.setToolTipText("");
        jScrollPaneFabricantes.setViewportView(jTableFabricantes);

        javax.swing.GroupLayout jInternalFabricantesLayout = new javax.swing.GroupLayout(jInternalFabricantes.getContentPane());
        jInternalFabricantes.getContentPane().setLayout(jInternalFabricantesLayout);
        jInternalFabricantesLayout.setHorizontalGroup(
            jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFabricantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalFabricantesLayout.createSequentialGroup()
                            .addComponent(jLabelIDFabricantes)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldIdFabricantes))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFabricantesLayout.createSequentialGroup()
                            .addComponent(jLabelNombreFabricantes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldNombreFabricantes))
                        .addGroup(jInternalFabricantesLayout.createSequentialGroup()
                            .addComponent(jButtonAgregarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonModificarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                            .addComponent(jButtonQuitarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFabricantesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFabricantesLayout.createSequentialGroup()
                                .addComponent(jComboBoxIDFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldCodigoFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jInternalFabricantesLayout.setVerticalGroup(
            jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFabricantesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDFabricantes)
                    .addComponent(jTextFieldIdFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreFabricantes)
                    .addComponent(jTextFieldNombreFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQuitarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jInternalFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIDFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFabricantes);
        jInternalFabricantes.setBounds(30, 80, 380, 420);

        jInternalCategorias.setTitle("Categorías");
        jInternalCategorias.setToolTipText("");
        jInternalCategorias.setVisible(true);

        jLabelIDCategorias.setText("Código:");

        jLabelNombreCategorias.setText("Nombre:");

        jTextFieldIDCategorias.setBackground(new java.awt.Color(240, 240, 240));

        jTextFieldNombreCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCategoriasActionPerformed(evt);
            }
        });

        jButtonAgregarCategorias.setText("Agregar");
        jButtonAgregarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCategoriasActionPerformed(evt);
            }
        });

        jButtonModificarCategorias.setText("Modificar");
        jButtonModificarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCategoriasActionPerformed(evt);
            }
        });

        jButtonQuitarCategorias.setText("Quitar");
        jButtonQuitarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarCategoriasActionPerformed(evt);
            }
        });

        jComboBoxIDCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombre" }));
        jComboBoxIDCategorias.setToolTipText("");
        jComboBoxIDCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDCategoriasActionPerformed(evt);
            }
        });

        jTextFieldCodigoCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoCategoriasActionPerformed(evt);
            }
        });

        jTableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCategorias.setToolTipText("");
        jScrollPaneCategorias.setViewportView(jTableCategorias);

        javax.swing.GroupLayout jInternalCategoriasLayout = new javax.swing.GroupLayout(jInternalCategorias.getContentPane());
        jInternalCategorias.getContentPane().setLayout(jInternalCategoriasLayout);
        jInternalCategoriasLayout.setHorizontalGroup(
            jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalCategoriasLayout.createSequentialGroup()
                            .addComponent(jLabelIDCategorias)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldIDCategorias))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalCategoriasLayout.createSequentialGroup()
                            .addComponent(jLabelNombreCategorias)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldNombreCategorias))
                        .addGroup(jInternalCategoriasLayout.createSequentialGroup()
                            .addComponent(jButtonAgregarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonModificarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                            .addComponent(jButtonQuitarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalCategoriasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalCategoriasLayout.createSequentialGroup()
                                .addComponent(jComboBoxIDCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldCodigoCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jInternalCategoriasLayout.setVerticalGroup(
            jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalCategoriasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDCategorias)
                    .addComponent(jTextFieldIDCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCategorias)
                    .addComponent(jTextFieldNombreCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQuitarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jInternalCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIDCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalCategorias);
        jInternalCategorias.setBounds(480, 70, 380, 420);

        jInternalBicicletas.setVisible(true);

        jLabelIDBicicletas.setText("Código:");

        jLabelModeloBicicletas.setText("Modelo:");

        jLabelTallaBicicletas.setText("Talla:");

        jLabelSuspensionBicicletas.setText("Suspensión:");

        jLabelTransmisionBicicletas.setText("Transmisión:");

        jLabelFrenosBicicletas.setText("Frenos:");

        jLabelStockBicicletas.setText("Stock:");

        jLabelValorBicicletas.setText("Valor:");

        jComboBoxIDBicicletas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombre" }));
        jComboBoxIDBicicletas.setToolTipText("");
        jComboBoxIDBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDBicicletasActionPerformed(evt);
            }
        });

        jTextFieldCodigoBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoBicicletasActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Talla", "Suspensión", "Transmisión", "Frenos", "Stock", "Valor", "Fabricante", "Categoría"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setMinimumSize(new java.awt.Dimension(750, 64));
        jScrollPane1.setViewportView(jTable1);

        jTextFieldIDBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDBicicletasActionPerformed(evt);
            }
        });

        jTextFieldModeloBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloBicicletasActionPerformed(evt);
            }
        });

        jTextFieldTallaBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTallaBicicletasActionPerformed(evt);
            }
        });

        jTextFieldSuspensionBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSuspensionBicicletasActionPerformed(evt);
            }
        });

        jTextFieldTransmisionBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransmisionBicicletasActionPerformed(evt);
            }
        });

        jButtonAgregarBicicletas.setText("Agregar");
        jButtonAgregarBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarBicicletasActionPerformed(evt);
            }
        });

        jButtonEditarBicicletas.setText("Editar");
        jButtonEditarBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarBicicletasActionPerformed(evt);
            }
        });

        jButtonEliminarBicicletas.setText("Quitar");
        jButtonEliminarBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarBicicletasActionPerformed(evt);
            }
        });

        jLabelFabricanteBicicletas.setText("Fabricante");

        jLabelCategoriaBicicletas.setText("Categoría");

        javax.swing.GroupLayout jInternalBicicletasLayout = new javax.swing.GroupLayout(jInternalBicicletas.getContentPane());
        jInternalBicicletas.getContentPane().setLayout(jInternalBicicletasLayout);
        jInternalBicicletasLayout.setHorizontalGroup(
            jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                                        .addComponent(jLabelModeloBicicletas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldModeloBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                                        .addComponent(jLabelIDBicicletas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldIDBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelSuspensionBicicletas)
                                    .addComponent(jLabelTallaBicicletas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSuspensionBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTallaBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTransmisionBicicletas)
                                    .addComponent(jLabelFrenosBicicletas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTransmisionBicicletas, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFrenosBicicletas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelStockBicicletas)
                                    .addComponent(jLabelValorBicicletas))
                                .addGap(26, 26, 26)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldStockBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValorBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelFabricanteBicicletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCategoriaBicicletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxFabricanteBicicletas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCategoriaBicicletas, 0, 113, Short.MAX_VALUE)))
                            .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                                .addComponent(jComboBoxIDBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCodigoBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jButtonAgregarBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditarBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonEliminarBicicletas))))
                    .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jInternalBicicletasLayout.setVerticalGroup(
            jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                        .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalBicicletasLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelIDBicicletas)
                                    .addComponent(jTextFieldIDBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalBicicletasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTallaBicicletas)
                                    .addComponent(jTextFieldTallaBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTransmisionBicicletas)
                                    .addComponent(jTextFieldTransmisionBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldStockBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelValorBicicletas)
                                    .addComponent(jLabelFabricanteBicicletas)
                                    .addComponent(jComboBoxFabricanteBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelModeloBicicletas)
                                .addComponent(jTextFieldModeloBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelSuspensionBicicletas)
                                .addComponent(jTextFieldSuspensionBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFrenosBicicletas)
                                .addComponent(jTextFieldFrenosBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldValorBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelStockBicicletas))))
                    .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCategoriaBicicletas)
                        .addComponent(jComboBoxCategoriaBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonEditarBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEliminarBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxIDBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCodigoBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAgregarBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalBicicletas);
        jInternalBicicletas.setBounds(80, 520, 1280, 400);

        jMenuArchivo.setMnemonic('a');
        jMenuArchivo.setText("Archivo");

        jMenuArchivoIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login_24x24.png"))); // NOI18N
        jMenuArchivoIngresar.setText("Ingresar");
        jMenuArchivo.add(jMenuArchivoIngresar);

        jMenuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuArchivoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit_24x24.png"))); // NOI18N
        jMenuArchivoSalir.setText("Salir");
        jMenuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArchivoSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuArchivoSalir);

        jMenuBarMain.add(jMenuArchivo);

        jMenuRegistrar.setMnemonic('r');
        jMenuRegistrar.setText("Registrar");

        jMenuRegistrarBicicleta.setText("Bicicleta");
        jMenuRegistrar.add(jMenuRegistrarBicicleta);

        jMenuRegistrarCategoria.setText("Categoria");
        jMenuRegistrar.add(jMenuRegistrarCategoria);

        jMenuRegistrarFabricante.setText("Fabricante");
        jMenuRegistrar.add(jMenuRegistrarFabricante);

        jMenuBarMain.add(jMenuRegistrar);

        jMenuInformes.setMnemonic('i');
        jMenuInformes.setText("Informes");

        jMenuInformesBici.setText("Listado de Bicis");
        jMenuInformes.add(jMenuInformesBici);

        jMenuBarMain.add(jMenuInformes);

        jMenuAyuda.setMnemonic('y');
        jMenuAyuda.setText("Ayuda");

        jMenuAyudaAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help_24x24.png"))); // NOI18N
        jMenuAyudaAcercaDe.setText("Acerca de ");
        jMenuAyuda.add(jMenuAyudaAcercaDe);

        jMenuBarMain.add(jMenuAyuda);

        setJMenuBar(jMenuBarMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArchivoSalirActionPerformed
        // al hacer click en "salir", este cierra la ventana
        this.dispose();
    }//GEN-LAST:event_jMenuArchivoSalirActionPerformed

    private void jTextFieldNombreFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreFabricantesActionPerformed

    private void jComboBoxIDFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDFabricantesActionPerformed

    private void jTextFieldCodigoFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoFabricantesActionPerformed

    private void jTextFieldNombreCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCategoriasActionPerformed

    private void jComboBoxIDCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDCategoriasActionPerformed

    private void jTextFieldCodigoCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoCategoriasActionPerformed

    private void jTextFieldCodigoBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoBicicletasActionPerformed

    private void jTextFieldIDBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDBicicletasActionPerformed

    private void jTextFieldModeloBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloBicicletasActionPerformed

    private void jTextFieldTallaBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTallaBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTallaBicicletasActionPerformed

    private void jTextFieldSuspensionBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSuspensionBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSuspensionBicicletasActionPerformed

    private void jButtonAgregarBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarBicicletasActionPerformed
        //registrarBicicleta();
    }//GEN-LAST:event_jButtonAgregarBicicletasActionPerformed

    private void jTextFieldTransmisionBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransmisionBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTransmisionBicicletasActionPerformed

    private void jButtonAgregarFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFabricantesActionPerformed
        registrarFabricante();
    }//GEN-LAST:event_jButtonAgregarFabricantesActionPerformed

    private void jButtonModificarFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarFabricantesActionPerformed

    private void jButtonQuitarFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuitarFabricantesActionPerformed

    private void jButtonAgregarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarCategoriasActionPerformed

    private void jButtonModificarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarCategoriasActionPerformed

    private void jButtonQuitarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuitarCategoriasActionPerformed

    private void jButtonEditarBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarBicicletasActionPerformed

    private void jButtonEliminarBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarBicicletasActionPerformed

    private void jComboBoxIDBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDBicicletasActionPerformed

    private void jTextFieldIdFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdFabricantesActionPerformed

 
    private void estadoInicial(){
        this.jInternalBicicletas.setVisible(false);
        this.jInternalCategorias.setVisible(false);
        this.jInternalFabricantes.setVisible(true);
        
    
    }
    
    private void registrarFabricante(){
        try
        {
            int ID = Integer.parseInt(this.jTextFieldIdFabricantes.getText());
            String nombre = this.jTextFieldNombreFabricantes.getText();
            Fabricante f = new Fabricante(ID, nombre);
            if(fc.create(f))
            {
                JOptionPane.showMessageDialog(null, "Fabricante registrado satisfactoriamente", "Mensajes", JOptionPane.INFORMATION_MESSAGE);
                //limpiarFormularioRegistroFabricantes();
                if(this.jInternalFabricantes.isVisible())
                {
                    cargarListadoFabricantes();

                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el Fabricante", "Mensajes", JOptionPane.ERROR_MESSAGE);
                this.jTextFieldNombreFabricantes.requestFocus();
                this.jTextFieldNombreFabricantes.selectAll();
            }
        }
        catch(CustomException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Mensajes", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldNombreFabricantes.requestFocus();
            this.jTextFieldNombreFabricantes.selectAll();
        
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Debes ingresar un código válido", "Mensajes", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldNombreFabricantes.requestFocus();
            this.jTextFieldNombreFabricantes.selectAll();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Mensajes", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldNombreFabricantes.requestFocus();
                this.jTextFieldNombreFabricantes.selectAll();
        }
      
    }
    
    private void cargarListadoFabricantes(){
        try
        {
            this.jComboBoxFabricanteBicicletas.removeAllItems();
            ArrayList<Fabricante> fabricantes = fc.readAll();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for(Fabricante f: fabricantes)
            {
                modelo.addElement (f);
            }
            this.jComboBoxFabricanteBicicletas.setModel(modelo);
            this.jComboBoxFabricanteBicicletas.setModel(modelo);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Problemas de conexión a la base de datos", "Mensajes", JOptionPane.ERROR_MESSAGE);
        }
    
    
    
    }
    
    private void modificarCargo(){
        try
        {
            int ID = Integer.parseInt(this.jTextFieldCodigoFabricantes.getText());
            String nombre = this.jTextFieldNombreFabricantes.getText();
            Fabricante f = new Fabricante(ID, nombre);
            if(fc.update(f))
            {
                JOptionPane.showMessageDialog(null, "Fabricante modificado satisfactoriamente", "mensajes", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormularioRegistroFabricantes();
                if(this.jInternalBicicletas.isVisible())
                {
                    cargarListadoFabricantes();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el Fabricante", "Mensajes", JOptionPane.ERROR_MESSAGE);
                this.jTextFieldNombreFabricantes.requestFocus();
                this.jTextFieldNombreFabricantes.selectAll();

            }
        }
       catch(CustomException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Mensajes", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldNombreFabricantes.requestFocus();
            this.jTextFieldNombreFabricantes.selectAll();
            
            
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Debes ingresar un código válido", "Mensajes", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldNombreFabricantes.requestFocus();
            this.jTextFieldNombreFabricantes.selectAll();
        }
        catch(HeadlessException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Mensajes", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldNombreFabricantes.requestFocus();
            this.jTextFieldNombreFabricantes.selectAll();
        }
    }
    
    
    
    
    
    

        
        
    
    
   
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainWindow().setVisible(true);
                MainWindow mw = new MainWindow();
                mw.setTitle("Proyecto Swing Bicicleta V0.1 001V");
                mw.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mw.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarBicicletas;
    private javax.swing.JButton jButtonAgregarCategorias;
    private javax.swing.JButton jButtonAgregarFabricantes;
    private javax.swing.JButton jButtonEditarBicicletas;
    private javax.swing.JButton jButtonEliminarBicicletas;
    private javax.swing.JButton jButtonModificarCategorias;
    private javax.swing.JButton jButtonModificarFabricantes;
    private javax.swing.JButton jButtonQuitarCategorias;
    private javax.swing.JButton jButtonQuitarFabricantes;
    private javax.swing.JComboBox<String> jComboBoxCategoriaBicicletas;
    private javax.swing.JComboBox<String> jComboBoxFabricanteBicicletas;
    private javax.swing.JComboBox<String> jComboBoxIDBicicletas;
    private javax.swing.JComboBox<String> jComboBoxIDCategorias;
    private javax.swing.JComboBox<String> jComboBoxIDFabricantes;
    private javax.swing.JInternalFrame jInternalBicicletas;
    private javax.swing.JInternalFrame jInternalCategorias;
    private javax.swing.JInternalFrame jInternalFabricantes;
    private javax.swing.JLabel jLabelCategoriaBicicletas;
    private javax.swing.JLabel jLabelFabricanteBicicletas;
    private javax.swing.JLabel jLabelFrenosBicicletas;
    private javax.swing.JLabel jLabelIDBicicletas;
    private javax.swing.JLabel jLabelIDCategorias;
    private javax.swing.JLabel jLabelIDFabricantes;
    private javax.swing.JLabel jLabelModeloBicicletas;
    private javax.swing.JLabel jLabelNombreCategorias;
    private javax.swing.JLabel jLabelNombreFabricantes;
    private javax.swing.JLabel jLabelStockBicicletas;
    private javax.swing.JLabel jLabelSuspensionBicicletas;
    private javax.swing.JLabel jLabelTallaBicicletas;
    private javax.swing.JLabel jLabelTransmisionBicicletas;
    private javax.swing.JLabel jLabelValorBicicletas;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuItem jMenuArchivoIngresar;
    private javax.swing.JMenuItem jMenuArchivoSalir;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuItem jMenuAyudaAcercaDe;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuInformesBici;
    private javax.swing.JMenu jMenuRegistrar;
    private javax.swing.JMenuItem jMenuRegistrarBicicleta;
    private javax.swing.JMenuItem jMenuRegistrarCategoria;
    private javax.swing.JMenuItem jMenuRegistrarFabricante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneCategorias;
    private javax.swing.JScrollPane jScrollPaneFabricantes;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCategorias;
    private javax.swing.JTable jTableFabricantes;
    private javax.swing.JTextField jTextFieldCodigoBicicletas;
    private javax.swing.JTextField jTextFieldCodigoCategorias;
    private javax.swing.JTextField jTextFieldCodigoFabricantes;
    private javax.swing.JTextField jTextFieldFrenosBicicletas;
    private javax.swing.JTextField jTextFieldIDBicicletas;
    private javax.swing.JTextField jTextFieldIDCategorias;
    private javax.swing.JTextField jTextFieldIdFabricantes;
    private javax.swing.JTextField jTextFieldModeloBicicletas;
    private javax.swing.JTextField jTextFieldNombreCategorias;
    private javax.swing.JTextField jTextFieldNombreFabricantes;
    private javax.swing.JTextField jTextFieldStockBicicletas;
    private javax.swing.JTextField jTextFieldSuspensionBicicletas;
    private javax.swing.JTextField jTextFieldTallaBicicletas;
    private javax.swing.JTextField jTextFieldTransmisionBicicletas;
    private javax.swing.JTextField jTextFieldValorBicicletas;
    // End of variables declaration//GEN-END:variables
}
